### ISSUE TITLE
Suggestion: move test text to a separate folder

### ISSUE THREAD

**Issue by goneall** [anshuldutt21/spdx_python_licensematching#10]
Currently, the license template and text files are in the same folder as the implementation code.  This make is hard to read.  Suggest moving to a separate folder such as testdata.

**Comment by anshuldutt21** [comment]
@goneall The template and text files that are in the same folder as the implementation one are just for testing. They will be removed once I complete the project. There is also a TemplateData folder which consists of all the templates in the source code which would mainly be used.

**Comment by anshuldutt21** [comment]
I thik we can close this issue now.
